// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv2li3zQ4IeffLZ-0cjGdGsBvqxCYnamo',
    appId: '1:970394434679:web:14c35d926acd9992849a72',
    messagingSenderId: '970394434679',
    projectId: 'corides-sineix',
    authDomain: 'corides-sineix.firebaseapp.com',
    storageBucket: 'corides-sineix.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhip6G4d3Sx5irpHGQu3frE_r06xXElUY',
    appId: '1:970394434679:android:71edb2d58492311d849a72',
    messagingSenderId: '970394434679',
    projectId: 'corides-sineix',
    storageBucket: 'corides-sineix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0YHOrqY8wv1Z8Wy7tKVLtOqZkVa2KbuE',
    appId: '1:970394434679:ios:3f50bff88d5d9830849a72',
    messagingSenderId: '970394434679',
    projectId: 'corides-sineix',
    storageBucket: 'corides-sineix.firebasestorage.app',
    iosBundleId: 'com.sineix.corides',
  );
}
